version: "3.7"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 411221174_apriantinuban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: 411221174_apriantinuban

  frontend:
    build: ./frontend
    ports:
      - "8081:80" # Frontend akan tersedia di port 80
    depends_on:
      - backend

volumes:
  postgres_data:
